version: '3.9'
services:
  db:
    image: postgres:14.4
    environment:
      - POSTGRES_PASSWORD=secrets
      - POSTGRES_USER=williamfong
    ports:
      - "5432:5432"
  test_runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .test_env
    volumes:
      - .:/testing
      - /tmp:/tmp
