services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: nox
    stdin_open: true
    tty: true

  # Service for running specific nox sessions
  nox:
    extends: test-runner
    command: ${NOX_SESSION:-nox}

  # Service for interactive development
  dev:
    extends: test-runner
    command: /bin/bash

  docs:
    extends: test-runner
    command: nox -s docs
