"""initializing

Revision ID: 818c30d98288
Revises:
Create Date: 2023-05-03 12:43:56.723433

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "818c30d98288"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "environments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("host", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_environments_created_on",
        "environments",
        ["created_on"],
        unique=False,
        postgresql_using="brin",
    )
    op.create_table(
        "libraries",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version"),
    )
    op.create_table(
        "variables",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", "value"),
    )
    op.create_table(
        "invocations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("user", sa.String(length=128), nullable=True),
        sa.Column("function", sa.String(length=128), nullable=True),
        sa.Column("environment_id", sa.BigInteger(), nullable=True),
        sa.Column("command", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_invocations_created_on",
        "invocations",
        ["created_on"],
        unique=False,
        postgresql_using="brin",
    )
    op.create_table(
        "library_environment_mappings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("environment_id", sa.BigInteger(), nullable=False),
        sa.Column("library_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("environment_id", "library_id"),
    )
    op.create_table(
        "variable_environment_mappings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("environment_id", sa.BigInteger(), nullable=False),
        sa.Column("variable_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variable_id"],
            ["variables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("environment_id", "variable_id"),
    )
    op.create_table(
        "data_products",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("invocation_id", sa.BigInteger(), nullable=True),
        sa.Column("mmh3_hash", sa.BigInteger(), nullable=True),
        sa.Column("path", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["invocation_id"],
            ["invocations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_data_products_created_on",
        "data_products",
        ["created_on"],
        unique=False,
        postgresql_using="brin",
    )
    op.create_table(
        "data_product_hierarchies",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("child_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["data_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["data_products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_data_product_hierarchies_created_on",
        "data_product_hierarchies",
        ["created_on"],
        unique=False,
        postgresql_using="brin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_data_product_hierarchies_created_on",
        table_name="data_product_hierarchies",
    )
    op.drop_table("data_product_hierarchies")
    op.drop_index("idx_data_products_created_on", table_name="data_products")
    op.drop_table("data_products")
    op.drop_table("variable_environment_mappings")
    op.drop_table("library_environment_mappings")
    op.drop_index("idx_invocations_created_on", table_name="invocations")
    op.drop_table("invocations")
    op.drop_table("variables")
    op.drop_table("libraries")
    op.drop_index("idx_environments_created_on", table_name="environments")
    op.drop_table("environments")
    # ### end Alembic commands ###
