"""swapping variable value column to text

Revision ID: 8f5a5370b95f
Revises: 818c30d98288
Create Date: 2023-05-03 14:30:50.433190

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8f5a5370b95f"
down_revision = "818c30d98288"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("variables", "value", type_=sa.Text())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("variables", "value", type_=sa.String(256))
    # ### end Alembic commands ###
